---
title: "From the instant to eternity"
author: "Yusup"
date: "2023-08-14"
categories: [linux]
---


Always had a fond inclination towards meditation.
I have been practicing meditation on and off for a couple years.  I even came up with my own methods of meditation, maybe that is for another post.

If I remember correctly I think Andrew Huberman once said that meditation is a special state in which you can upgrade your source code of your brain/consciousness.

There are many things we don't know enough about, and mind/brain is one of them.

I tried Bhagavad Gita a couple of times but got intimidated by the names and characters as they are all Hindi. 
It is hard to memorize long names as you have no idea how the Hindi names are constructed. Somehow I pulled through, and finished the book gladly.

There are a lot can be learned from the Gita. What struck me the most is the immortality of `self` .

Discourse 2, Bhagavad Gita

> The self is not born
nor does it ever die.
Once it has been, this self will
never cease to be again.
Unborn, eternal,
continuing from the old,
the self is not killed
when the body is killed


Discourse 2, Bhagavad Gita

>And as you discern
your own dharma,
you should not waver.
For the warrio,
htere can be found
nothing greater
than battle 
for the sake of dharma.



The idea is that you are immortal, thus have no fear, face your enemies, pursue your dharma.


>Your authority is
in action alone,
and never 
in its fruits;
motive should never be 
in the fruits of action,
nor should  you cling to inaction

Focus on action, not the results, live a meditative life.

Bhagavad Gita means the song of the God. It is as poetic and as beautiful as it can be. It is a book that you can read over and over again, and you will always find something new.


After finishing the Gita, I started reading Meditations by Marcus Aurelius. 

Meditations is a stark contrast to Bhagavad Gita, as Marcus Aurelius is brought upon the knowledge of Greek golden age, in which logic and reason are the main pillars of the society. 
It also has totally different take on death, that we all die, and we might die at any given moment.



Book 2

>You may leave this life at any moment: 
have this possibility in your mind in all that you do or say or think.

Book 3

>So we must have sense of urgency, not only for the ever closer approach of death, 
but also because our comprehension of 
the world and our ability to pay proper attention will fade before we do.


Death is maybe imminent and we should take every action as the last one we can take. 
This brings the same liberation that Bhagavad Gita brings, although they are achieved by different angles.


Book 4

>No action should be undertaken without aim, 
or other than in conformity with principle affirming the art of life.

Book 7 

>Remember these two things: the action is important, the context indifferent.

One from the east and one from the west, one is spiritual, and the other is logical, and core ideas somehow converge one way or another. 
Both are astoundingly beautiful and full of wisdom.
