---
title: "Show limited respect"
author: "Yusup"
date: "2023-12-21"
categories: [thoughts]
toc: true
execute:
  warning: true
  error: true
  debug: true
---

# Show limited respect

Lately I've listened to the audiobook "Elon Musk" by Walter Isaacson.

Here are a few things I've learned from the book.

1. question everything, every requirement, especially the smart people, because they are not challenged enough.
2. delete unnecessary steps, if you are not adding back 10% after deletion, you are not deleting enough.
3. simplify the process
4. optimize cycle performance
5. automate everything
6. risk appetite, he has a high risk appetite, he is willing to take risks, and he is willing to fail.
7. only thing you should respect is the laws of physics, everything else is just a recommendation.

He has a unique way dealing with the external environment, and he has clear set of visions and goals from the get go, which is something I might have lost along the way.

Could you ask yourself when was the last time you were passionate about something and you made conscious effort to pursue it?

> I don't wanna be a product of my environment. I want my environment to be a product of me. - Frank Costello, The Departed

By in large we live in hierarchical structures, and structure has its own rules and its inertia.

At every social structural level, you are requested & demanded to act certain way. These are the "rules".

Only few few few of the people can remind you that you should follow your own dreams and your own rules.

Honestly, I've forgotten the last big thing I've wanted to achieve. I was forged to become someone else.

The joy and the passion of the pursuit of your dream is the most important thing in your life.

No amount of forced "deep work" or heavily structured "productivity" hacks can replace the joy of the pursuit of your dream or alas lasts that long.

Don't lose dreams, not to the environment you are in, not to the people you are with, not to the rules you are following.


```{=html}
<div style="position: relative; padding-top: 56.95652173913044%;">
  <iframe
    src="https://customer-xyomvvsceqirni02.cloudflarestream.com/d3a6fa47e843bd528047320f61f4047a/iframe?poster=https%3A%2F%2Fcustomer-xyomvvsceqirni02.cloudflarestream.com%2Fd3a6fa47e843bd528047320f61f4047a%2Fthumbnails%2Fthumbnail.jpg%3Ftime%3D%26height%3D600"
    allow="accelerometer; gyroscope; autoplay; encrypted-media;"
    allowfullscreen="false"
  ></iframe>
</div>
```
