---
title: "Metaconsciousness"
author: "Yusup"
date: "2023-10-09"
categories: [thoughts]
toc: true
execute:
  warning: true
  error: true
  debug: true
---

# Metaconscious


Till now,  we still don't know how the brain works.  Although, in the east, west there are different schools of thoughts 
on how to meditate and how to control the brain how to live a life. 

I think we are getting far less and less spiritual and the same with our capacity to getting into the flow of meditation state.

We do rely on medications and pills to regulate our moods.

To me, having full control thoughts, emotions, feelings is like a superpower.  Cause we get derailed by all sort of emotions and thoughts from time to time.
We might have different ambitions and plans, we might never reach our destination as we are not a in-control pilots.

In terms of people who can control their thoughts and emotions, I could think of David Goggins, and monks from the east.

They can override their pain and thoughts. It is higher awareness than can govern bodily impulses and thoughts and fears. 

Meditation is like mental model where you can grab hold of your attention and thoughts, or it is more about learn how to focus and control things.
It takes lot's of practice and dedication. Nothing is free.

People might have different names for this capacity, but I think it is metaconsciousness at work.

Imagine standing in the lounge of a hotel, and you can see doors on the both sides. Each door represents some sort of impulse or need of yours.

You can choose to open the door and let the impulse in, or you can choose to ignore it.

When troubled, always remember you are the one who can choose to open the door or not, and there are many doors to choose from.